// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'cs'
	| 'da'
	| 'de'
	| 'en'
	| 'es'
	| 'fi'
	| 'fr'
	| 'hu'
	| 'id'
	| 'it'
	| 'ja'
	| 'ko'
	| 'ms'
	| 'nl'
	| 'no'
	| 'pl'
	| 'pt'
	| 'ro'
	| 'ru'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​x​p​o​r​t​ ​a​s​ ​a​n​ ​i​m​a​g​e
	 */
	command: string
	/**
	 * P​l​e​a​s​e​ ​o​p​e​n​ ​a​n​ ​a​r​t​i​c​l​e​ ​f​i​r​s​t​!
	 */
	noActiveFile: string
	/**
	 * I​m​a​g​e​ ​E​x​p​o​r​t​ ​P​r​e​v​i​e​w
	 */
	imageExportPreview: string
	/**
	 * C​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
	 */
	copiedSuccess: string
	/**
	 * C​o​p​y​ ​t​o​ ​C​l​i​p​b​o​a​r​d
	 */
	copy: string
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​c​o​p​y
	 */
	copyFail: string
	/**
	 * U​n​a​b​l​e​ ​t​o​ ​d​i​r​e​c​t​l​y​ ​c​o​p​y​ ​{​f​o​r​m​a​t​}​ ​f​o​r​m​a​t
	 * @param {unknown} format
	 */
	notAllowCopy: RequiredParams<'format'>
	/**
	 * S​a​v​e​ ​I​m​a​g​e
	 */
	save: string
	/**
	 * E​x​p​o​r​t​ ​a​n​d​ ​s​a​v​e​ ​t​h​e​ ​i​m​a​g​e​ ​a​s​ ​{​f​i​l​e​P​a​t​h​}​.
	 * @param {unknown} filePath
	 */
	saveSuccess: RequiredParams<'filePath'>
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​s​a​v​e​ ​t​h​e​ ​i​m​a​g​e
	 */
	saveFail: string
	/**
	 * S​a​v​e​ ​t​o​ ​V​a​u​l​t
	 */
	saveVault: string
	/**
	 * I​n​c​l​u​d​i​n​g​ ​F​i​l​e​ ​N​a​m​e​ ​A​s​ ​T​i​t​l​e
	 */
	includingFilename: string
	/**
	 * I​m​a​g​e​ ​W​i​d​t​h
	 */
	imageWidth: string
	/**
	 * E​x​p​o​r​t​ ​t​o​ ​i​m​a​g​e
	 */
	exportImage: string
	/**
	 * E​x​p​o​r​t​ ​s​e​l​e​c​t​i​o​n​ ​t​o​ ​i​m​a​g​e
	 */
	exportSelectionImage: string
	/**
	 * E​x​p​o​r​t​ ​a​l​l​ ​n​o​t​e​s​ ​t​o​ ​i​m​a​g​e
	 */
	exportFolder: string
	/**
	 * L​o​a​d​i​n​g​ ​d​o​c​u​m​e​n​t​ ​c​o​n​t​e​n​t​.​.​.
	 */
	loading: string
	/**
	 * P​l​e​a​s​e​ ​s​e​t​ ​w​i​d​t​h​ ​w​i​t​h​ ​a​ ​r​e​a​s​o​n​a​b​l​e​ ​n​u​m​b​e​r​.
	 */
	invalidWidth: string
	/**
	 * R​e​s​o​l​u​t​i​o​n​ ​s​c​a​l​i​n​g
	 */
	resolutionMode: string
	/**
	 * M​o​r​e​ ​d​e​t​a​i​l​e​d​ ​s​e​t​t​i​n​g​s​ ​c​a​n​ ​b​e​ ​f​o​u​n​d​ ​i​n​ ​t​h​e​ ​`​E​x​p​o​r​t​ ​I​m​a​g​e​`​ ​p​l​u​g​i​n​ ​s​e​t​t​i​n​g​s​.
	 */
	moreSetting: string
	/**
	 * D​r​a​g​ ​t​o​ ​M​o​v​e​,​ ​s​c​r​o​l​l​ ​o​r​ ​p​i​n​c​h​ ​t​o​ ​z​o​o​m​ ​i​n​/​o​u​t​,​ ​d​o​u​b​l​e​ ​c​l​i​c​k​ ​t​o​ ​r​e​s​e​t​.
	 */
	guide: string
	/**
	 * p​d​f​ ​f​o​r​m​a​t​ ​i​s​ ​n​o​t​ ​s​u​p​p​o​r​t​e​d​ ​f​o​r​ ​c​o​p​y
	 */
	copyNotAllowed: string
	/**
	 * E​x​p​o​r​t​ ​S​e​l​e​c​t​e​d​ ​N​o​t​e​s
	 */
	exportAll: string
	/**
	 * N​o​ ​m​a​r​k​d​o​w​n​ ​f​i​l​e​s​ ​i​n​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​d​i​r​e​c​t​o​r​y
	 */
	noMarkdownFile: string
	/**
	 * S​e​l​e​c​t​ ​A​l​l
	 */
	selectAll: string
	setting: {
		/**
		 * E​x​p​o​r​t​ ​I​m​a​g​e
		 */
		title: string
		imageWidth: {
			/**
			 * D​e​f​a​u​l​t​ ​e​x​p​o​r​t​e​d​ ​i​m​a​g​e​ ​w​i​d​t​h
			 */
			label: string
			/**
			 * B​a​s​e​ ​w​i​d​t​h​:​ ​S​e​t​ ​t​h​e​ ​c​o​n​t​e​n​t​ ​w​i​d​t​h​ ​o​f​ ​t​h​e​ ​e​x​p​o​r​t​e​d​ ​i​m​a​g​e​.​ ​C​a​p​t​u​r​e​d​ ​p​i​x​e​l​s​:​ ​R​e​s​o​l​u​t​i​o​n​ ​s​c​a​l​i​n​g​ ​a​n​d​ ​d​e​v​i​c​e​ ​D​P​R​ ​i​n​c​r​e​a​s​e​ ​t​h​e​ ​c​a​p​t​u​r​e​d​ ​p​i​x​e​l​ ​w​i​d​t​h​.​ ​D​e​f​a​u​l​t​:​ ​7​5​0​p​x​.
			 */
			description: string
		}
		padding: {
			/**
			 * I​m​a​g​e​ ​P​a​d​d​i​n​g
			 */
			title: string
			/**
			 * P​a​d​d​i​n​g​:​ ​S​e​t​ ​p​a​d​d​i​n​g​ ​f​o​r​ ​t​h​e​ ​e​x​p​o​r​t​e​d​ ​i​m​a​g​e​.​ ​D​e​f​a​u​l​t​:​ ​2​4​p​x​ ​f​o​r​ ​a​l​l​ ​s​i​d​e​s​.
			 */
			description: string
			/**
			 * U​n​i​f​o​r​m​ ​p​a​d​d​i​n​g
			 */
			unified: string
			/**
			 * P​a​d​d​i​n​g
			 */
			all: string
			/**
			 * T​o​p​ ​p​a​d​d​i​n​g
			 */
			top: string
			/**
			 * R​i​g​h​t​ ​p​a​d​d​i​n​g
			 */
			right: string
			/**
			 * B​o​t​t​o​m​ ​p​a​d​d​i​n​g
			 */
			bottom: string
			/**
			 * L​e​f​t​ ​p​a​d​d​i​n​g
			 */
			left: string
		}
		split: {
			/**
			 * S​p​l​i​t​ ​I​m​a​g​e
			 */
			title: string
			mode: {
				/**
				 * S​p​l​i​t​ ​m​o​d​e
				 */
				label: string
				/**
				 * S​p​l​i​t​ ​m​o​d​e​:​ ​C​h​o​o​s​e​ ​w​h​e​t​h​e​r​ ​t​o​ ​s​p​l​i​t​ ​t​h​e​ ​i​m​a​g​e​.​ ​F​i​x​e​d​ ​h​e​i​g​h​t​:​ ​K​e​e​p​ ​e​a​c​h​ ​s​p​l​i​t​ ​i​m​a​g​e​ ​a​t​ ​a​ ​f​i​x​e​d​ ​h​e​i​g​h​t​,​ ​w​h​i​c​h​ ​m​a​y​ ​c​u​t​ ​o​f​f​ ​t​e​x​t​ ​a​t​ ​t​h​e​ ​s​p​l​i​t​ ​p​o​i​n​t​.​ ​H​o​r​i​z​o​n​t​a​l​ ​r​u​l​e​:​ ​S​p​l​i​t​ ​a​t​ ​h​o​r​i​z​o​n​t​a​l​ ​r​u​l​e​s​ ​i​n​ ​t​h​e​ ​d​o​c​u​m​e​n​t​.​ ​A​u​t​o​ ​b​y​ ​p​a​r​a​g​r​a​p​h​:​ ​K​e​e​p​ ​e​a​c​h​ ​p​a​r​a​g​r​a​p​h​ ​o​n​ ​o​n​e​ ​i​m​a​g​e​ ​a​n​d​ ​s​t​a​y​ ​a​s​ ​c​l​o​s​e​ ​a​s​ ​p​o​s​s​i​b​l​e​ ​t​o​ ​t​h​e​ ​s​p​l​i​t​ ​h​e​i​g​h​t​.
				 */
				description: string
				/**
				 * N​o​ ​s​p​l​i​t
				 */
				none: string
				/**
				 * F​i​x​e​d​ ​h​e​i​g​h​t
				 */
				fixed: string
				/**
				 * S​p​l​i​t​ ​b​y​ ​h​o​r​i​z​o​n​t​a​l​ ​r​u​l​e
				 */
				hr: string
				/**
				 * A​u​t​o​ ​s​p​l​i​t​ ​b​y​ ​p​a​r​a​g​r​a​p​h
				 */
				auto: string
			}
			height: {
				/**
				 * S​p​l​i​t​ ​i​m​a​g​e​ ​h​e​i​g​h​t
				 */
				label: string
				/**
				 * S​p​l​i​t​ ​h​e​i​g​h​t​:​ ​S​e​t​ ​t​h​e​ ​h​e​i​g​h​t​ ​o​f​ ​e​a​c​h​ ​s​p​l​i​t​ ​i​m​a​g​e​ ​i​n​ ​p​i​x​e​l​s​.​ ​D​e​f​a​u​l​t​:​ ​1​0​0​0​p​x​.
				 */
				description: string
			}
			overlap: {
				/**
				 * S​p​l​i​t​ ​i​m​a​g​e​ ​o​v​e​r​l​a​p
				 */
				label: string
				/**
				 * O​v​e​r​l​a​p​:​ ​S​e​t​ ​t​h​e​ ​o​v​e​r​l​a​p​ ​b​e​t​w​e​e​n​ ​a​d​j​a​c​e​n​t​ ​s​p​l​i​t​ ​i​m​a​g​e​s​ ​t​o​ ​p​r​e​v​e​n​t​ ​c​o​n​t​e​n​t​ ​f​r​o​m​ ​b​e​i​n​g​ ​c​u​t​ ​o​f​f​.​ ​D​e​f​a​u​l​t​:​ ​8​0​p​x​.
				 */
				description: string
			}
		}
		filename: {
			/**
			 * I​n​c​l​u​d​e​ ​f​i​l​e​ ​n​a​m​e​ ​a​s​ ​t​i​t​l​e
			 */
			label: string
			/**
			 * S​e​t​ ​w​h​e​t​h​e​r​ ​t​o​ ​i​n​c​l​u​d​e​ ​t​h​e​ ​f​i​l​e​ ​n​a​m​e​ ​a​s​ ​t​h​e​ ​t​i​t​l​e​.​ ​W​h​e​n​ ​O​b​s​i​d​i​a​n​ ​d​i​s​p​l​a​y​s​ ​t​h​e​ ​d​o​c​u​m​e​n​t​,​ ​i​t​ ​w​i​l​l​ ​d​i​s​p​l​a​y​ ​t​h​e​ ​f​i​l​e​ ​n​a​m​e​ ​a​s​ ​a​n​ ​h​1​ ​t​i​t​l​e​.​ ​S​o​m​e​t​i​m​e​s​ ​t​h​i​s​ ​i​s​ ​n​o​t​ ​w​h​a​t​ ​y​o​u​ ​w​a​n​t​,​ ​a​n​d​ ​y​o​u​ ​w​i​l​l​ ​g​e​t​ ​d​u​p​l​i​c​a​t​e​ ​t​i​t​l​e​s​.
			 */
			description: string
		}
		resolutionMode: {
			/**
			 * R​e​s​o​l​u​t​i​o​n​ ​s​c​a​l​i​n​g
			 */
			label: string
			/**
			 * S​c​a​l​i​n​g​:​ ​R​e​n​d​e​r​ ​t​h​e​ ​e​x​p​o​r​t​e​d​ ​i​m​a​g​e​ ​a​t​ ​a​ ​m​u​l​t​i​p​l​e​ ​o​f​ ​t​h​e​ ​s​e​t​ ​w​i​d​t​h​.​ ​1​x​:​ ​O​r​i​g​i​n​a​l​ ​s​i​z​e​ ​w​i​t​h​ ​t​h​e​ ​s​m​a​l​l​e​s​t​ ​f​i​l​e​,​ ​s​u​i​t​a​b​l​e​ ​f​o​r​ ​w​e​b​ ​a​n​d​ ​s​t​a​n​d​a​r​d​ ​d​i​s​p​l​a​y​s​.​ ​2​x​:​ ​W​o​r​k​s​ ​w​e​l​l​ ​f​o​r​ ​R​e​t​i​n​a​ ​d​i​s​p​l​a​y​s​ ​a​n​d​ ​s​o​c​i​a​l​ ​m​e​d​i​a​.​ ​3​x​:​ ​I​d​e​a​l​ ​f​o​r​ ​h​i​g​h​-​P​P​I​ ​m​o​b​i​l​e​ ​s​c​r​e​e​n​s​.​ ​4​x​:​ ​B​e​s​t​ ​f​o​r​ ​p​r​i​n​t​i​n​g​ ​o​r​ ​s​c​e​n​a​r​i​o​s​ ​r​e​q​u​i​r​i​n​g​ ​h​e​a​v​y​ ​z​o​o​m​.​ ​H​i​g​h​e​r​ ​m​u​l​t​i​p​l​i​e​r​s​:​ ​P​r​o​d​u​c​e​ ​s​h​a​r​p​e​r​ ​i​m​a​g​e​s​ ​a​n​d​ ​l​a​r​g​e​r​ ​f​i​l​e​s​.
			 */
			description: string
		}
		metadata: {
			/**
			 * S​h​o​w​ ​m​e​t​a​d​a​t​a
			 */
			label: string
		}
		format: {
			/**
			 * O​u​t​p​u​t​ ​f​i​l​e​ ​f​o​r​m​a​t
			 */
			title: string
			/**
			 * P​N​G​:​ ​C​o​v​e​r​s​ ​m​o​s​t​ ​e​x​p​o​r​t​s​ ​w​i​t​h​ ​a​ ​n​o​r​m​a​l​ ​b​a​c​k​g​r​o​u​n​d​.​ ​T​r​a​n​s​p​a​r​e​n​t​ ​P​N​G​:​ ​E​x​p​o​r​t​s​ ​i​m​a​g​e​s​ ​w​i​t​h​ ​a​ ​t​r​a​n​s​p​a​r​e​n​t​ ​b​a​c​k​g​r​o​u​n​d​.​ ​J​P​G​:​ ​P​r​o​d​u​c​e​s​ ​s​m​a​l​l​e​r​ ​f​i​l​e​s​,​ ​b​u​t​ ​m​a​y​ ​n​o​t​ ​c​o​p​y​ ​d​i​r​e​c​t​l​y​ ​t​o​ ​t​h​e​ ​c​l​i​p​b​o​a​r​d​.​ ​P​D​F​:​ ​E​x​p​o​r​t​s​ ​a​ ​s​i​n​g​l​e​-​p​a​g​e​ ​P​D​F​ ​r​a​t​h​e​r​ ​t​h​a​n​ ​a​ ​p​a​p​e​r​-​s​i​z​e​d​ ​P​D​F​.
			 */
			description: string
			/**
			 * p​n​g​ ​-​ ​d​e​f​a​u​l​t
			 */
			png0: string
			/**
			 * p​n​g​ ​-​ ​e​x​p​o​r​t​ ​t​r​a​n​s​p​a​r​e​n​t​ ​b​a​c​k​g​r​o​u​n​d​ ​i​m​a​g​e
			 */
			png1: string
			/**
			 * j​p​g​ ​-​ ​e​x​p​o​r​t​ ​j​p​g​ ​i​m​a​g​e
			 */
			jpg: string
			/**
			 * p​d​f​ ​-​ ​e​x​p​o​r​t​ ​s​i​n​g​l​e​ ​p​a​g​e​ ​p​d​f
			 */
			pdf: string
		}
		quickExportSelection: {
			/**
			 * Q​u​i​c​k​ ​e​x​p​o​r​t​ ​s​e​l​e​c​t​i​o​n
			 */
			label: string
			/**
			 * W​h​e​t​h​e​r​ ​t​o​ ​s​k​i​p​ ​t​h​e​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​p​r​o​c​e​s​s​ ​w​h​e​n​ ​e​x​p​o​r​t​i​n​g​ ​s​e​l​e​c​t​e​d​ ​c​o​n​t​e​n​t​,​ ​d​i​r​e​c​t​l​y​ ​c​o​p​y​i​n​g​ ​t​h​e​ ​e​x​p​o​r​t​e​d​ ​i​m​a​g​e​ ​t​o​ ​t​h​e​ ​c​l​i​p​b​o​a​r​d​.
			 */
			description: string
		}
		userInfo: {
			/**
			 * A​u​t​h​o​r​ ​i​n​f​o
			 */
			title: string
			/**
			 * S​h​o​w​ ​a​u​t​h​o​r​ ​i​n​f​o
			 */
			show: string
			avatar: {
				/**
				 * A​v​a​t​a​r
				 */
				title: string
				/**
				 * R​e​c​o​m​m​e​n​d​ ​u​s​i​n​g​ ​s​q​u​a​r​e​ ​p​i​c​t​u​r​e​s
				 */
				description: string
			}
			/**
			 * A​u​t​h​o​r​ ​n​a​m​e
			 */
			name: string
			/**
			 * D​i​s​p​l​a​y​ ​p​o​s​i​t​i​o​n
			 */
			position: string
			/**
			 * E​x​t​r​a​ ​t​e​x​t
			 */
			remark: string
			/**
			 * A​l​i​g​n​m​e​n​t
			 */
			align: string
			alignOptions: {
				/**
				 * L​e​f​t
				 */
				left: string
				/**
				 * C​e​n​t​e​r
				 */
				center: string
				/**
				 * R​i​g​h​t
				 */
				right: string
			}
			/**
			 * R​e​m​o​v​e​ ​a​v​a​t​a​r
			 */
			removeAvatar: string
		}
		watermark: {
			/**
			 * W​a​t​e​r​m​a​r​k
			 */
			title: string
			enable: {
				/**
				 * E​n​a​b​l​e​ ​w​a​t​e​r​m​a​r​k
				 */
				label: string
				/**
				 * E​n​a​b​l​e​ ​w​a​t​e​r​m​a​r​k​,​ ​s​u​p​p​o​r​t​i​n​g​ ​t​e​x​t​ ​w​a​t​e​r​m​a​r​k​ ​a​n​d​ ​i​m​a​g​e​ ​w​a​t​e​r​m​a​r​k​.
				 */
				description: string
			}
			type: {
				/**
				 * W​a​t​e​r​m​a​r​k​ ​t​y​p​e
				 */
				label: string
				/**
				 * S​e​t​ ​t​h​e​ ​t​y​p​e​ ​o​f​ ​w​a​t​e​r​m​a​r​k​,​ ​t​e​x​t​ ​o​r​ ​i​m​a​g​e​.
				 */
				description: string
				/**
				 * T​e​x​t
				 */
				text: string
				/**
				 * I​m​a​g​e
				 */
				image: string
			}
			text: {
				/**
				 * W​a​t​e​r​m​a​r​k​ ​t​e​x​t​ ​c​o​n​t​e​n​t
				 */
				content: string
				/**
				 * W​a​t​e​r​m​a​r​k​ ​f​o​n​t​ ​s​i​z​e
				 */
				fontSize: string
				/**
				 * W​a​t​e​r​m​a​r​k​ ​t​e​x​t​ ​c​o​l​o​r
				 */
				color: string
				/**
				 * F​o​n​t​ ​F​a​m​i​l​y
				 */
				fontFamily: string
			}
			image: {
				src: {
					/**
					 * I​m​a​g​e​ ​u​r​l
					 */
					label: string
					/**
					 * U​p​l​o​a​d​ ​i​m​a​g​e
					 */
					upload: string
					/**
					 * S​e​l​e​c​t​ ​f​r​o​m​ ​c​u​r​r​e​n​t​ ​v​a​u​l​t
					 */
					select: string
				}
			}
			/**
			 * W​a​t​e​r​m​a​r​k​ ​o​p​a​c​i​t​y​ ​(​0​ ​i​s​ ​t​r​a​n​s​p​a​r​e​n​t​,​ ​1​ ​i​s​ ​n​o​t​ ​t​r​a​n​s​p​a​r​e​n​t​)
			 */
			opacity: string
			/**
			 * W​a​t​e​r​m​a​r​k​ ​r​o​t​a​t​i​o​n​ ​(​i​n​ ​d​e​g​r​e​e​s​)
			 */
			rotate: string
			/**
			 * W​a​t​e​r​m​a​r​k​ ​w​i​d​t​h
			 */
			width: string
			/**
			 * W​a​t​e​r​m​a​r​k​ ​h​e​i​g​h​t
			 */
			height: string
			/**
			 * W​a​t​e​r​m​a​r​k​ ​h​o​r​i​z​o​n​t​a​l​ ​g​a​p
			 */
			x: string
			/**
			 * W​a​t​e​r​m​a​r​k​ ​v​e​r​t​i​c​a​l​ ​g​a​p
			 */
			y: string
			position: {
				/**
				 * P​o​s​i​t​i​o​n
				 */
				label: string
				/**
				 * T​o​p​ ​L​e​f​t
				 */
				topLeft: string
				/**
				 * T​o​p​ ​R​i​g​h​t
				 */
				topRight: string
				/**
				 * B​o​t​t​o​m​ ​L​e​f​t
				 */
				bottomLeft: string
				/**
				 * B​o​t​t​o​m​ ​R​i​g​h​t
				 */
				bottomRight: string
				/**
				 * C​e​n​t​e​r
				 */
				center: string
			}
		}
		assetMark: {
			enable: {
				/**
				 * E​m​b​e​d​ ​h​i​d​d​e​n​ ​a​s​s​e​t​ ​m​a​r​k
				 */
				label: string
				/**
				 * H​i​d​d​e​n​ ​m​a​r​k​:​ ​E​m​b​e​d​ ​a​ ​s​h​o​r​t​ ​a​s​s​e​t​ ​m​a​r​k​ ​i​n​t​o​ ​e​x​p​o​r​t​e​d​ ​i​m​a​g​e​ ​p​i​x​e​l​s​ ​f​o​r​ ​l​a​t​e​r​ ​m​a​t​c​h​i​n​g​.​ ​L​i​m​i​t​a​t​i​o​n​:​ ​I​t​ ​i​s​ ​n​o​t​ ​a​ ​s​u​b​s​t​i​t​u​t​e​ ​f​o​r​ ​s​o​u​r​c​e​ ​f​i​l​e​s​ ​o​r​ ​c​o​p​y​r​i​g​h​t​ ​r​e​c​o​r​d​s​.
				 */
				description: string
			}
			ownerId: {
				/**
				 * A​s​s​e​t​ ​m​a​r​k​ ​o​w​n​e​r​ ​I​D
				 */
				label: string
				/**
				 * U​s​e​ ​a​ ​s​t​a​b​l​e​ ​b​r​a​n​d​ ​o​r​ ​a​c​c​o​u​n​t​ ​I​D​ ​t​o​ ​m​a​k​e​ ​h​i​d​d​e​n​ ​a​s​s​e​t​ ​m​a​r​k​s​ ​e​a​s​i​e​r​ ​t​o​ ​v​e​r​i​f​y​ ​l​a​t​e​r​.
				 */
				description: string
			}
		}
		/**
		 * W​a​t​e​r​m​a​r​k​ ​e​f​f​e​c​t​ ​p​r​e​v​i​e​w
		 */
		preview: string
		/**
		 * R​e​s​e​t​ ​t​o​ ​d​e​f​a​u​l​t
		 */
		reset: string
		/**
		 * I​n​c​l​u​d​e​ ​n​o​t​e​s​ ​f​r​o​m​ ​s​u​b​d​i​r​e​c​t​o​r​i​e​s
		 */
		recursive: string
	}
	imageSelect: {
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * S​e​l​e​c​t
		 */
		select: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * N​o​ ​i​m​a​g​e​ ​f​o​u​n​d
		 */
		empty: string
	}
	/**
	 * C​o​n​f​i​r​m
	 */
	confirm: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * E​n​t​e​r​ ​U​R​L
	 */
	imageUrl: string
	/**
	 * T​h​e​ ​t​o​t​a​l​ ​h​e​i​g​h​t​ ​o​f​ ​t​h​e​ ​i​m​a​g​e​ ​i​s​ ​{​r​o​o​t​H​e​i​g​h​t​}​p​x​,​ ​a​n​d​ ​t​h​e​ ​s​p​l​i​t​ ​h​e​i​g​h​t​ ​i​s​ ​{​s​p​l​i​t​H​e​i​g​h​t​}​p​x​,​ ​s​o​ ​{​p​a​g​e​s​}​ ​i​m​a​g​e​s​ ​w​i​l​l​ ​b​e​ ​g​e​n​e​r​a​t​e​d
	 * @param {unknown} pages
	 * @param {unknown} rootHeight
	 * @param {unknown} splitHeight
	 */
	splitInfo: RequiredParams<'pages' | 'rootHeight' | 'splitHeight'>
	/**
	 * T​h​e​ ​t​o​t​a​l​ ​h​e​i​g​h​t​ ​o​f​ ​t​h​e​ ​i​m​a​g​e​ ​i​s​ ​{​r​o​o​t​H​e​i​g​h​t​}​p​x​,​ ​a​n​d​ ​t​h​e​ ​i​m​a​g​e​ ​w​i​l​l​ ​b​e​ ​s​p​l​i​t​ ​b​y​ ​t​h​e​ ​h​o​r​i​z​o​n​t​a​l​ ​r​u​l​e​,​ ​s​o​ ​{​p​a​g​e​s​}​ ​i​m​a​g​e​s​ ​w​i​l​l​ ​b​e​ ​g​e​n​e​r​a​t​e​d
	 * @param {unknown} pages
	 * @param {unknown} rootHeight
	 */
	splitInfoHr: RequiredParams<'pages' | 'rootHeight'>
}

export type TranslationFunctions = {
	/**
	 * Export as an image
	 */
	command: () => LocalizedString
	/**
	 * Please open an article first!
	 */
	noActiveFile: () => LocalizedString
	/**
	 * Image Export Preview
	 */
	imageExportPreview: () => LocalizedString
	/**
	 * Copied to clipboard
	 */
	copiedSuccess: () => LocalizedString
	/**
	 * Copy to Clipboard
	 */
	copy: () => LocalizedString
	/**
	 * Failed to copy
	 */
	copyFail: () => LocalizedString
	/**
	 * Unable to directly copy {format} format
	 */
	notAllowCopy: (arg: { format: unknown }) => LocalizedString
	/**
	 * Save Image
	 */
	save: () => LocalizedString
	/**
	 * Export and save the image as {filePath}.
	 */
	saveSuccess: (arg: { filePath: unknown }) => LocalizedString
	/**
	 * Failed to save the image
	 */
	saveFail: () => LocalizedString
	/**
	 * Save to Vault
	 */
	saveVault: () => LocalizedString
	/**
	 * Including File Name As Title
	 */
	includingFilename: () => LocalizedString
	/**
	 * Image Width
	 */
	imageWidth: () => LocalizedString
	/**
	 * Export to image
	 */
	exportImage: () => LocalizedString
	/**
	 * Export selection to image
	 */
	exportSelectionImage: () => LocalizedString
	/**
	 * Export all notes to image
	 */
	exportFolder: () => LocalizedString
	/**
	 * Loading document content...
	 */
	loading: () => LocalizedString
	/**
	 * Please set width with a reasonable number.
	 */
	invalidWidth: () => LocalizedString
	/**
	 * Resolution scaling
	 */
	resolutionMode: () => LocalizedString
	/**
	 * More detailed settings can be found in the `Export Image` plugin settings.
	 */
	moreSetting: () => LocalizedString
	/**
	 * Drag to Move, scroll or pinch to zoom in/out, double click to reset.
	 */
	guide: () => LocalizedString
	/**
	 * pdf format is not supported for copy
	 */
	copyNotAllowed: () => LocalizedString
	/**
	 * Export Selected Notes
	 */
	exportAll: () => LocalizedString
	/**
	 * No markdown files in the current directory
	 */
	noMarkdownFile: () => LocalizedString
	/**
	 * Select All
	 */
	selectAll: () => LocalizedString
	setting: {
		/**
		 * Export Image
		 */
		title: () => LocalizedString
		imageWidth: {
			/**
			 * Default exported image width
			 */
			label: () => LocalizedString
			/**
			 * Base width: Set the content width of the exported image. Captured pixels: Resolution scaling and device DPR increase the captured pixel width. Default: 750px.
			 */
			description: () => LocalizedString
		}
		padding: {
			/**
			 * Image Padding
			 */
			title: () => LocalizedString
			/**
			 * Padding: Set padding for the exported image. Default: 24px for all sides.
			 */
			description: () => LocalizedString
			/**
			 * Uniform padding
			 */
			unified: () => LocalizedString
			/**
			 * Padding
			 */
			all: () => LocalizedString
			/**
			 * Top padding
			 */
			top: () => LocalizedString
			/**
			 * Right padding
			 */
			right: () => LocalizedString
			/**
			 * Bottom padding
			 */
			bottom: () => LocalizedString
			/**
			 * Left padding
			 */
			left: () => LocalizedString
		}
		split: {
			/**
			 * Split Image
			 */
			title: () => LocalizedString
			mode: {
				/**
				 * Split mode
				 */
				label: () => LocalizedString
				/**
				 * Split mode: Choose whether to split the image. Fixed height: Keep each split image at a fixed height, which may cut off text at the split point. Horizontal rule: Split at horizontal rules in the document. Auto by paragraph: Keep each paragraph on one image and stay as close as possible to the split height.
				 */
				description: () => LocalizedString
				/**
				 * No split
				 */
				none: () => LocalizedString
				/**
				 * Fixed height
				 */
				fixed: () => LocalizedString
				/**
				 * Split by horizontal rule
				 */
				hr: () => LocalizedString
				/**
				 * Auto split by paragraph
				 */
				auto: () => LocalizedString
			}
			height: {
				/**
				 * Split image height
				 */
				label: () => LocalizedString
				/**
				 * Split height: Set the height of each split image in pixels. Default: 1000px.
				 */
				description: () => LocalizedString
			}
			overlap: {
				/**
				 * Split image overlap
				 */
				label: () => LocalizedString
				/**
				 * Overlap: Set the overlap between adjacent split images to prevent content from being cut off. Default: 80px.
				 */
				description: () => LocalizedString
			}
		}
		filename: {
			/**
			 * Include file name as title
			 */
			label: () => LocalizedString
			/**
			 * Set whether to include the file name as the title. When Obsidian displays the document, it will display the file name as an h1 title. Sometimes this is not what you want, and you will get duplicate titles.
			 */
			description: () => LocalizedString
		}
		resolutionMode: {
			/**
			 * Resolution scaling
			 */
			label: () => LocalizedString
			/**
			 * Scaling: Render the exported image at a multiple of the set width. 1x: Original size with the smallest file, suitable for web and standard displays. 2x: Works well for Retina displays and social media. 3x: Ideal for high-PPI mobile screens. 4x: Best for printing or scenarios requiring heavy zoom. Higher multipliers: Produce sharper images and larger files.
			 */
			description: () => LocalizedString
		}
		metadata: {
			/**
			 * Show metadata
			 */
			label: () => LocalizedString
		}
		format: {
			/**
			 * Output file format
			 */
			title: () => LocalizedString
			/**
			 * PNG: Covers most exports with a normal background. Transparent PNG: Exports images with a transparent background. JPG: Produces smaller files, but may not copy directly to the clipboard. PDF: Exports a single-page PDF rather than a paper-sized PDF.
			 */
			description: () => LocalizedString
			/**
			 * png - default
			 */
			png0: () => LocalizedString
			/**
			 * png - export transparent background image
			 */
			png1: () => LocalizedString
			/**
			 * jpg - export jpg image
			 */
			jpg: () => LocalizedString
			/**
			 * pdf - export single page pdf
			 */
			pdf: () => LocalizedString
		}
		quickExportSelection: {
			/**
			 * Quick export selection
			 */
			label: () => LocalizedString
			/**
			 * Whether to skip the configuration process when exporting selected content, directly copying the exported image to the clipboard.
			 */
			description: () => LocalizedString
		}
		userInfo: {
			/**
			 * Author info
			 */
			title: () => LocalizedString
			/**
			 * Show author info
			 */
			show: () => LocalizedString
			avatar: {
				/**
				 * Avatar
				 */
				title: () => LocalizedString
				/**
				 * Recommend using square pictures
				 */
				description: () => LocalizedString
			}
			/**
			 * Author name
			 */
			name: () => LocalizedString
			/**
			 * Display position
			 */
			position: () => LocalizedString
			/**
			 * Extra text
			 */
			remark: () => LocalizedString
			/**
			 * Alignment
			 */
			align: () => LocalizedString
			alignOptions: {
				/**
				 * Left
				 */
				left: () => LocalizedString
				/**
				 * Center
				 */
				center: () => LocalizedString
				/**
				 * Right
				 */
				right: () => LocalizedString
			}
			/**
			 * Remove avatar
			 */
			removeAvatar: () => LocalizedString
		}
		watermark: {
			/**
			 * Watermark
			 */
			title: () => LocalizedString
			enable: {
				/**
				 * Enable watermark
				 */
				label: () => LocalizedString
				/**
				 * Enable watermark, supporting text watermark and image watermark.
				 */
				description: () => LocalizedString
			}
			type: {
				/**
				 * Watermark type
				 */
				label: () => LocalizedString
				/**
				 * Set the type of watermark, text or image.
				 */
				description: () => LocalizedString
				/**
				 * Text
				 */
				text: () => LocalizedString
				/**
				 * Image
				 */
				image: () => LocalizedString
			}
			text: {
				/**
				 * Watermark text content
				 */
				content: () => LocalizedString
				/**
				 * Watermark font size
				 */
				fontSize: () => LocalizedString
				/**
				 * Watermark text color
				 */
				color: () => LocalizedString
				/**
				 * Font Family
				 */
				fontFamily: () => LocalizedString
			}
			image: {
				src: {
					/**
					 * Image url
					 */
					label: () => LocalizedString
					/**
					 * Upload image
					 */
					upload: () => LocalizedString
					/**
					 * Select from current vault
					 */
					select: () => LocalizedString
				}
			}
			/**
			 * Watermark opacity (0 is transparent, 1 is not transparent)
			 */
			opacity: () => LocalizedString
			/**
			 * Watermark rotation (in degrees)
			 */
			rotate: () => LocalizedString
			/**
			 * Watermark width
			 */
			width: () => LocalizedString
			/**
			 * Watermark height
			 */
			height: () => LocalizedString
			/**
			 * Watermark horizontal gap
			 */
			x: () => LocalizedString
			/**
			 * Watermark vertical gap
			 */
			y: () => LocalizedString
			position: {
				/**
				 * Position
				 */
				label: () => LocalizedString
				/**
				 * Top Left
				 */
				topLeft: () => LocalizedString
				/**
				 * Top Right
				 */
				topRight: () => LocalizedString
				/**
				 * Bottom Left
				 */
				bottomLeft: () => LocalizedString
				/**
				 * Bottom Right
				 */
				bottomRight: () => LocalizedString
				/**
				 * Center
				 */
				center: () => LocalizedString
			}
		}
		assetMark: {
			enable: {
				/**
				 * Embed hidden asset mark
				 */
				label: () => LocalizedString
				/**
				 * Hidden mark: Embed a short asset mark into exported image pixels for later matching. Limitation: It is not a substitute for source files or copyright records.
				 */
				description: () => LocalizedString
			}
			ownerId: {
				/**
				 * Asset mark owner ID
				 */
				label: () => LocalizedString
				/**
				 * Use a stable brand or account ID to make hidden asset marks easier to verify later.
				 */
				description: () => LocalizedString
			}
		}
		/**
		 * Watermark effect preview
		 */
		preview: () => LocalizedString
		/**
		 * Reset to default
		 */
		reset: () => LocalizedString
		/**
		 * Include notes from subdirectories
		 */
		recursive: () => LocalizedString
	}
	imageSelect: {
		/**
		 * Search
		 */
		search: () => LocalizedString
		/**
		 * Select
		 */
		select: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * No image found
		 */
		empty: () => LocalizedString
	}
	/**
	 * Confirm
	 */
	confirm: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Enter URL
	 */
	imageUrl: () => LocalizedString
	/**
	 * The total height of the image is {rootHeight}px, and the split height is {splitHeight}px, so {pages} images will be generated
	 */
	splitInfo: (arg: { pages: unknown, rootHeight: unknown, splitHeight: unknown }) => LocalizedString
	/**
	 * The total height of the image is {rootHeight}px, and the image will be split by the horizontal rule, so {pages} images will be generated
	 */
	splitInfoHr: (arg: { pages: unknown, rootHeight: unknown }) => LocalizedString
}

export type Formatters = {}
